//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeAttendance.Model.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employee()
        {
            this.TimeAttendanceLog = new HashSet<TimeAttendanceLog>();
        }
    
        public string EmployeeId { get; set; }
        public string DepartmentId { get; set; }
        public string JobTitleId { get; set; }
        public string FaceId { get; set; }
        public string Name { get; set; }
        public string Code { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public Nullable<int> Gender { get; set; }
        public Nullable<System.DateTime> InComeDate { get; set; }
        public Nullable<System.DateTime> OutComeDate { get; set; }
        public string Address { get; set; }
        public string IdentifyCardNumber { get; set; }
        public string Description { get; set; }
        public string LinkImageFaceId { get; set; }
        public string LinkImage { get; set; }
        public string CreateBy { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
    
        public virtual Department Department { get; set; }
        public virtual JobTitle JobTitle { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TimeAttendanceLog> TimeAttendanceLog { get; set; }
    }
}
