//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeAttendance.Model.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class GroupPermission
    {
        public string GroupPermissionId { get; set; }
        public string GroupId { get; set; }
        public string FunctionId { get; set; }
    
        public virtual Function Function { get; set; }
        public virtual Function Function1 { get; set; }
        public virtual Group Group { get; set; }
        public virtual Group Group1 { get; set; }
    }
}
