//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeAttendance.Model.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class SyncTimeAttendance
    {
        public string SyncAttendanceId { get; set; }
        public string EmployeeId { get; set; }
        public string EmployeeName { get; set; }
        public string Code { get; set; }
        public string Gender { get; set; }
        public string DepartmentName { get; set; }
        public string JobTitleName { get; set; }
        public System.DateTime Date { get; set; }
        public Nullable<System.DateTime> TimeIn { get; set; }
        public Nullable<System.DateTime> TimeOut { get; set; }
        public Nullable<int> Total { get; set; }
        public Nullable<int> LateMinutes { get; set; }
        public Nullable<int> EarlyMinutes { get; set; }
        public Nullable<bool> IsLate { get; set; }
        public Nullable<bool> IsEarly { get; set; }
        public Nullable<bool> IsAbsent { get; set; }
    }
}
