//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeAttendance.Model.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class TimeAttendanceLog
    {
        public string TimeAttendanceLogId { get; set; }
        public string EmployeeId { get; set; }
        public System.DateTime Date { get; set; }
        public Nullable<System.DateTime> TimeIn { get; set; }
        public string ImageIn { get; set; }
        public Nullable<System.DateTime> TimeOut { get; set; }
        public string ImageOut { get; set; }
        public Nullable<int> Total { get; set; }
        public Nullable<int> LateMinutes { get; set; }
        public Nullable<int> EarlyMinutes { get; set; }
        public string ImageFaceIn { get; set; }
        public string ImageFaceOut { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
