//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeAttendance.Model.Repositories
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TimeAttendanceEntities : DbContext
    {
        public TimeAttendanceEntities()
            : base("name=TimeAttendanceEntities")
        {
        }
        public TimeAttendanceEntities(string connStr)
             : base(connStr)
        {
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AttendanceLog> AttendanceLog { get; set; }
        public virtual DbSet<Department> Department { get; set; }
        public virtual DbSet<Employee> Employee { get; set; }
        public virtual DbSet<Function> Function { get; set; }
        public virtual DbSet<Group> Group { get; set; }
        public virtual DbSet<GroupFunction> GroupFunction { get; set; }
        public virtual DbSet<GroupPermission> GroupPermission { get; set; }
        public virtual DbSet<JobTitle> JobTitle { get; set; }
        public virtual DbSet<SyncTimeAttendance> SyncTimeAttendance { get; set; }
        public virtual DbSet<SystemParam> SystemParam { get; set; }
        public virtual DbSet<TimeAttendanceLog> TimeAttendanceLog { get; set; }
        public virtual DbSet<TransactionLog> TransactionLog { get; set; }
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<UserEventLog> UserEventLog { get; set; }
        public virtual DbSet<UserGroup> UserGroup { get; set; }
        public virtual DbSet<UserPermission> UserPermission { get; set; }
    }
}
