//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeAttendance.Model.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserEventLog
    {
        public string UserEventLogId { get; set; }
        public string ViolationEventId { get; set; }
        public string UserId { get; set; }
        public string Description { get; set; }
        public Nullable<int> LogType { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
    }
}
